backend:
  name: git-gateway
  branch: main
  identity_url: "https://radiant-malabi-45554d.netlify.app/.netlify/identity"
  gateway_url: "https://radiant-malabi-45554d.netlify.app/.netlify/git"

media_folder: "images/pages"
public_folder: "/images/pages"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.json"
        label: "Home"
        name: "home"
        format: "json"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
      
      - file: "content/contact.json"
        label: "Contacto"
        name: "contact"
        format: "json"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Teléfono", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Dirección", name: "address", widget: "text" }
